quarkus:
  application:
    name: quarkus-eureka-client
  http:
    port: 8686
    non-application-root-path: /actuators/eureka-client
  eureka:
    host-name: localhost
    health-check-url: /actuators/eureka-client/health
    status-page-url: /actuators/eureka-client/health
    prefer-ip-address: false
    service-url:
      default: http://${quarkus.eureka.host-name}:8761/eureka
    vip-address: localhost

  micrometer:
    export:
      prometheus:
        path: /actuators/eureka-client/promethus

  smallrye-openapi:
    enable: true


  camel:
   api:
     base-path: /services/camel
     openapi-path: /v2/api-docs
   service:
     dummy:
       create: http://dummy.restapiexample.com/api/v1/create
